### ISSUE TITLE
您好，请教一个问题

### ISSUE THREAD

**Issue by liangc40K** [QiShare/QiSignInWithApple#1]
拿userId( userId ==credential.user 存储起来的)，每次启动App时通过getCredentialStateForUserID去验证状态时，每次都返回ASAuthorizationAppleIDProviderCredentialNotFound，这是怎么回事呢？

**Comment by twototwoto** [comment]
你好，我没遇到相关问题。我调用getCredentialStateForUserID返回正常的ASAuthorizationAppleIDProviderCredentialAuthorized。

建议你再查看下getCredentialStateForUserID使用的credential.user吧。


下边是我的credential.user是可以正常使用的。你可以比对一下和你使用的credential.user 格式是否一致。
(lldb) po userIdentifier
0xxxx9.xxxx1988bb054e91beec303a4d0xxxxx.xxx6

(lldb) po userIdentifier.length
44

(lldb) po [userIdentifier componentsSeparatedByString:@"."]
<__NSArrayM 0x2839bb6c0>(
0xxxx9,
xxxx1988bb054e91beec303a4d0xxxxx,
xxx6
)

(lldb) po [userIdentifier componentsSeparatedByString:@"."][0].length
6

(lldb) po [userIdentifier componentsSeparatedByString:@"."][1].length
32

(lldb) po [userIdentifier componentsSeparatedByString:@"."][2].length
4

**Comment by liangc40K** [comment]
您好，下班回家试试了。我的userId长度和结构都和你贴出来的一样。仍然失败了，下载您的Demo也试试了，也失败了。我猜估计是模拟器测试，我都是用模拟器测试的。
